#!/bin/bash

# ./scripts/ci/frontend-build  
# ./scripts/buildx -t nginx-proxy-manager:2.10.4-oidc
# docker save nginx-proxy-manager:2.10.4-oidc > ./nginx-proxy-manager-oidc.tar
# scp ./nginx-proxy-manager-oidc.tar proxy.geo-satis.com:/home/dandrei

BUILD_VERSION=$(cat ../.version)

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. "$DIR/.common.sh"

echo -e "${BLUE}❯ ${CYAN}Building docker multiarch: ${YELLOW}${*}${RESET}"

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${DIR}/.." || exit 1

# determine commit if not already set
if [ "$BUILD_COMMIT" == "" ]; then
	BUILD_COMMIT=$(git log -n 1 --format=%h)
fi

# Buildx Builder
docker buildx create --name "${BUILDX_NAME:-npm}" || echo
docker buildx use "${BUILDX_NAME:-npm}"

docker buildx build \
	--build-arg BUILD_VERSION="${BUILD_VERSION:-dev}" \
	--build-arg BUILD_COMMIT="${BUILD_COMMIT:-notset}" \
	--build-arg BUILD_DATE="$(date '+%Y-%m-%d %T %Z')" \
	--build-arg GOPROXY="${GOPROXY:-}" \
	--build-arg GOPRIVATE="${GOPRIVATE:-}" \
	--platform linux/amd64 \
	--progress plain \
	--pull \
	--load \
	-f docker/Dockerfile \
	$@ \
	. 

rc=$?
docker buildx rm "${BUILDX_NAME:-npm}"
echo -e "${BLUE}❯ ${GREEN}Multiarch build Complete${RESET}"
exit $rc
